version: '3.4'

services:
  realestatewebapi.webapi:
    image: ${DOCKER_REGISTRY-}realestatewebapiwebapi
    build:
      context: .
      dockerfile: Presentation/RealEstateWebApi.WebApi/Dockerfile

  realestatewebapi.webapp:
    image: ${DOCKER_REGISTRY-}realestatewebapiwebapp
    build:
      context: .
      dockerfile: Presentation/RealEstateWebApi.WebApp/Dockerfile

  psqlcomposedata:
    image: postgres:latest
