// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RealEstateWebApi.Persistence.Contexts;

#nullable disable

namespace RealEstateWebApi.Persistence.Migrations
{
    [DbContext(typeof(RealEstateWebApiDbContext))]
    [Migration("20221118111924_mig_12")]
    partial class mig_12
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RealEstateWebApi.Domain.Entities.Agent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("FacebookUrl")
                        .HasColumnType("text");

                    b.Property<string>("InstagramUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<long>("JobTitleId")
                        .HasColumnType("bigint");

                    b.Property<string>("LinkedinUrl")
                        .HasColumnType("text");

                    b.Property<string>("TwitterUrl")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ViewMobileNumber")
                        .HasColumnType("text");

                    b.Property<string>("ViewPhoneNumber")
                        .HasColumnType("text");

                    b.Property<string>("YoutubeProfileUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("JobTitleId");

                    b.ToTable("Agents");
                });

            modelBuilder.Entity("RealEstateWebApi.Domain.Entities.Blog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AgentId")
                        .HasColumnType("bigint");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("BlogPageImgFileId")
                        .HasColumnType("bigint");

                    b.Property<long>("BlogTypeId")
                        .HasColumnType("bigint");

                    b.Property<long>("ClientId")
                        .HasColumnType("bigint");

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("BlogPageImgFileId");

                    b.HasIndex("BlogTypeId");

                    b.HasIndex("ClientId");

                    b.HasIndex("CompanyId");

                    b.ToTable("Blogs");
                });

            modelBuilder.Entity("RealEstateWebApi.Domain.Entities.BlogType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ClientId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("BlogTypes");
                });

            modelBuilder.Entity("RealEstateWebApi.Domain.Entities.City", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Key")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("RealEstateWebApi.Domain.Entities.Client", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("About")
                        .HasColumnType("text");

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<string>("ContactAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Dns")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FacebookUrl")
                        .HasColumnType("text");

                    b.Property<string>("InstagramUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LinkedinUrl")
                        .HasColumnType("text");

                    b.Property<long?>("LogoImgFileId")
                        .HasColumnType("bigint");

                    b.Property<string>("SummaryInfo")
                        .HasColumnType("text");

                    b.Property<string>("TwitterUrl")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ViewName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("LogoImgFileId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("RealEstateWebApi.Domain.Entities.Company", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("StartingYear")
                        .HasColumnType("integer");

                    b.Property<string>("TaxAdministration")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("TaxNumber")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("RealEstateWebApi.Domain.Entities.Customer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AssignedUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("BirthDay")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("CitizenNumber")
                        .HasColumnType("bigint");

                    b.Property<long>("CityId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("DistrictId")
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MobileNumber2")
                        .HasColumnType("text");

                    b.Property<long?>("NeighborhoodId")
                        .HasColumnType("bigint");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber2")
                        .HasColumnType("text");

                    b.Property<long>("RegisterUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("DistrictId");

                    b.HasIndex("NeighborhoodId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("RealEstateWebApi.Domain.Entities.CustomerOwnedShortProperty", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<string>("EjLink")
                        .HasColumnType("text");

                    b.Property<string>("HeLink")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("OtherLink")
                        .HasColumnType("text");

                    b.Property<long?>("PropertyId")
                        .HasColumnType("bigint");

                    b.Property<string>("ShLink")
                        .HasColumnType("text");

                    b.Property<long>("ShortPropertyId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("PropertyId");

                    b.HasIndex("ShortPropertyId");

                    b.ToTable("CustomerOwnedShortProperties");
                });

            modelBuilder.Entity("RealEstateWebApi.Domain.Entities.CustomerSearchShortProperty", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<long>("ShortPropertyId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ShortPropertyId");

                    b.ToTable("CustomerSearchShortProperties");
                });

            modelBuilder.Entity("RealEstateWebApi.Domain.Entities.DeedStatus", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("DeedStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedDate = new DateTime(2022, 11, 18, 11, 19, 21, 977, DateTimeKind.Utc).AddTicks(3221),
                            IsActive = true,
                            IsDeleted = false,
                            Title = "Kat Mülkiyetli"
                        },
                        new
                        {
                            Id = 2L,
                            CreatedDate = new DateTime(2022, 11, 18, 11, 19, 21, 977, DateTimeKind.Utc).AddTicks(3226),
                            IsActive = true,
                            IsDeleted = false,
                            Title = "Kat İrtifaklı"
                        },
                        new
                        {
                            Id = 3L,
                            CreatedDate = new DateTime(2022, 11, 18, 11, 19, 21, 977, DateTimeKind.Utc).AddTicks(3228),
                            IsActive = true,
                            IsDeleted = false,
                            Title = "Arsa"
                        },
                        new
                        {
                            Id = 4L,
                            CreatedDate = new DateTime(2022, 11, 18, 11, 19, 21, 977, DateTimeKind.Utc).AddTicks(3229),
                            IsActive = true,
                            IsDeleted = false,
                            Title = "Tarla"
                        });
                });

            modelBuilder.Entity("RealEstateWebApi.Domain.Entities.District", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("CityKey")
                        .HasColumnType("integer");

                    b.Property<int>("Key")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Districts");
                });

            modelBuilder.Entity("RealEstateWebApi.Domain.Entities.Entry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<string>("EntrySubTitle")
                        .HasColumnType("text");

                    b.Property<long>("EntrySubTypeId")
                        .HasColumnType("bigint");

                    b.Property<long>("EntryTypeId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("EntrySubTypeId");

                    b.HasIndex("EntryTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("Entries");
                });

            modelBuilder.Entity("RealEstateWebApi.Domain.Entities.EntrySubType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("EntryTypeId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EntryTypeId");

                    b.ToTable("EntrySubTypes");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedDate = new DateTime(2022, 11, 18, 11, 19, 21, 980, DateTimeKind.Utc).AddTicks(3547),
                            EntryTypeId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Title = "Ziyaret"
                        },
                        new
                        {
                            Id = 2L,
                            CreatedDate = new DateTime(2022, 11, 18, 11, 19, 21, 980, DateTimeKind.Utc).AddTicks(3551),
                            EntryTypeId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Title = "Telefon"
                        });
                });

            modelBuilder.Entity("RealEstateWebApi.Domain.Entities.EntryType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("EntryTypes");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedDate = new DateTime(2022, 11, 18, 11, 19, 21, 980, DateTimeKind.Utc).AddTicks(4329),
                            IsActive = true,
                            IsDeleted = false,
                            Title = "Görüşme"
                        });
                });

            modelBuilder.Entity("RealEstateWebApi.Domain.Entities.File", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Storage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Files");

                    b.HasDiscriminator<string>("Discriminator").HasValue("File");
                });

            modelBuilder.Entity("RealEstateWebApi.Domain.Entities.Front", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Fronts");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedDate = new DateTime(2022, 11, 18, 11, 19, 21, 980, DateTimeKind.Utc).AddTicks(5073),
                            IsActive = true,
                            IsDeleted = false,
                            Title = "Kuzey"
                        },
                        new
                        {
                            Id = 2L,
                            CreatedDate = new DateTime(2022, 11, 18, 11, 19, 21, 980, DateTimeKind.Utc).AddTicks(5076),
                            IsActive = true,
                            IsDeleted = false,
                            Title = "Kuzey Doğu"
                        },
                        new
                        {
                            Id = 3L,
                            CreatedDate = new DateTime(2022, 11, 18, 11, 19, 21, 980, DateTimeKind.Utc).AddTicks(5078),
                            IsActive = true,
                            IsDeleted = false,
                            Title = "Doğu"
                        },
                        new
                        {
                            Id = 4L,
                            CreatedDate = new DateTime(2022, 11, 18, 11, 19, 21, 980, DateTimeKind.Utc).AddTicks(5079),
                            IsActive = true,
                            IsDeleted = false,
                            Title = "Güney Doğu"
                        },
                        new
                        {
                            Id = 5L,
                            CreatedDate = new DateTime(2022, 11, 18, 11, 19, 21, 980, DateTimeKind.Utc).AddTicks(5081),
                            IsActive = true,
                            IsDeleted = false,
                            Title = "Güney"
                        },
                        new
                        {
                            Id = 6L,
                            CreatedDate = new DateTime(2022, 11, 18, 11, 19, 21, 980, DateTimeKind.Utc).AddTicks(5082),
                            IsActive = true,
                            IsDeleted = false,
                            Title = "Güney Batı"
                        },
                        new
                        {
                            Id = 7L,
                            CreatedDate = new DateTime(2022, 11, 18, 11, 19, 21, 980, DateTimeKind.Utc).AddTicks(5084),
                            IsActive = true,
                            IsDeleted = false,
                            Title = "Batı"
                        },
                        new
                        {
                            Id = 8L,
                            CreatedDate = new DateTime(2022, 11, 18, 11, 19, 21, 980, DateTimeKind.Utc).AddTicks(5085),
                            IsActive = true,
                            IsDeleted = false,
                            Title = "Kuzey Batı"
                        });
                });

            modelBuilder.Entity("RealEstateWebApi.Domain.Entities.HeatingType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("HeatingTypes");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedDate = new DateTime(2022, 11, 18, 11, 19, 21, 980, DateTimeKind.Utc).AddTicks(6088),
                            IsActive = true,
                            IsDeleted = false,
                            Title = "Doğalgaz Sobalı"
                        },
                        new
                        {
                            Id = 2L,
                            CreatedDate = new DateTime(2022, 11, 18, 11, 19, 21, 980, DateTimeKind.Utc).AddTicks(6092),
                            IsActive = true,
                            IsDeleted = false,
                            Title = "Sobalı"
                        },
                        new
                        {
                            Id = 3L,
                            CreatedDate = new DateTime(2022, 11, 18, 11, 19, 21, 980, DateTimeKind.Utc).AddTicks(6094),
                            IsActive = true,
                            IsDeleted = false,
                            Title = "Yerden Isıtma"
                        },
                        new
                        {
                            Id = 4L,
                            CreatedDate = new DateTime(2022, 11, 18, 11, 19, 21, 980, DateTimeKind.Utc).AddTicks(6095),
                            IsActive = true,
                            IsDeleted = false,
                            Title = "Kombili"
                        },
                        new
                        {
                            Id = 5L,
                            CreatedDate = new DateTime(2022, 11, 18, 11, 19, 21, 980, DateTimeKind.Utc).AddTicks(6096),
                            IsActive = true,
                            IsDeleted = false,
                            Title = "Merkezi Sistem"
                        },
                        new
                        {
                            Id = 6L,
                            CreatedDate = new DateTime(2022, 11, 18, 11, 19, 21, 980, DateTimeKind.Utc).AddTicks(6098),
                            IsActive = true,
                            IsDeleted = false,
                            Title = "FuelOil"
                        });
                });

            modelBuilder.Entity("RealEstateWebApi.Domain.Entities.Identity.OperationClaim", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Alias")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("OperationClaims");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Alias = "ADMIN",
                            CreatedDate = new DateTime(2022, 11, 18, 11, 19, 21, 982, DateTimeKind.Utc).AddTicks(5131),
                            Description = "Admin account",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2L,
                            Alias = "USER",
                            CreatedDate = new DateTime(2022, 11, 18, 11, 19, 21, 982, DateTimeKind.Utc).AddTicks(5138),
                            Description = "User account",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "User"
                        },
                        new
                        {
                            Id = 3L,
                            Alias = "AGENT",
                            CreatedDate = new DateTime(2022, 11, 18, 11, 19, 21, 982, DateTimeKind.Utc).AddTicks(5140),
                            Description = "Agent account",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Agent"
                        });
                });

            modelBuilder.Entity("RealEstateWebApi.Domain.Entities.Identity.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("CitizenNumber")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("PassHash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("PassSalt")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<long?>("ProfileImgFileId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProfileImgFileId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RealEstateWebApi.Domain.Entities.Identity.UserLogin", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("RefreshTokenExpireDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("UserLogins");
                });

            modelBuilder.Entity("RealEstateWebApi.Domain.Entities.Identity.UserOperationClaim", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<long>("OperationClaimId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OperationClaimId");

                    b.HasIndex("UserId");

                    b.ToTable("UserOperationClaims");
                });

            modelBuilder.Entity("RealEstateWebApi.Domain.Entities.InternetType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("InternetTypes");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedDate = new DateTime(2022, 11, 18, 11, 19, 21, 980, DateTimeKind.Utc).AddTicks(6904),
                            IsActive = true,
                            IsDeleted = false,
                            Title = "Adsl/Vdsl"
                        },
                        new
                        {
                            Id = 2L,
                            CreatedDate = new DateTime(2022, 11, 18, 11, 19, 21, 980, DateTimeKind.Utc).AddTicks(6907),
                            IsActive = true,
                            IsDeleted = false,
                            Title = "Fiber"
                        },
                        new
                        {
                            Id = 3L,
                            CreatedDate = new DateTime(2022, 11, 18, 11, 19, 21, 980, DateTimeKind.Utc).AddTicks(6909),
                            IsActive = true,
                            IsDeleted = false,
                            Title = "Uydu"
                        },
                        new
                        {
                            Id = 4L,
                            CreatedDate = new DateTime(2022, 11, 18, 11, 19, 21, 980, DateTimeKind.Utc).AddTicks(6910),
                            IsActive = true,
                            IsDeleted = false,
                            Title = "Altyapı Yok"
                        });
                });

            modelBuilder.Entity("RealEstateWebApi.Domain.Entities.JobTitle", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("JobTitles");
                });

            modelBuilder.Entity("RealEstateWebApi.Domain.Entities.Message", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ClientId")
                        .HasColumnType("bigint");

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("SenderEmail")
                        .HasColumnType("text");

                    b.Property<string>("SenderMobile")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SenderName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("CompanyId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("RealEstateWebApi.Domain.Entities.Neighborhood", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("DistrictKey")
                        .HasColumnType("integer");

                    b.Property<int>("Key")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Neighborhoods");
                });

            modelBuilder.Entity("RealEstateWebApi.Domain.Entities.Property", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AgentId")
                        .HasColumnType("bigint");

                    b.Property<double?>("Aidat")
                        .HasColumnType("double precision");

                    b.Property<int?>("BalconyCount")
                        .HasColumnType("integer");

                    b.Property<int?>("BathRoomCount")
                        .HasColumnType("integer");

                    b.Property<int>("BuildingAge")
                        .HasColumnType("integer");

                    b.Property<int>("BuildingFloor")
                        .HasColumnType("integer");

                    b.Property<int>("BuildingTotalFloor")
                        .HasColumnType("integer");

                    b.Property<long>("CityId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ClientId")
                        .HasColumnType("bigint");

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("DeedStatusId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("DistrictId")
                        .HasColumnType("bigint");

                    b.Property<long>("FrontId")
                        .HasColumnType("bigint");

                    b.Property<int?>("GarageCount")
                        .HasColumnType("integer");

                    b.Property<int>("GrossSquareMeter")
                        .HasColumnType("integer");

                    b.Property<long>("HeatingTypeId")
                        .HasColumnType("bigint");

                    b.Property<long>("InternetTypeId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsAvailableLoan")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFurnished")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOnSite")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSmartHome")
                        .HasColumnType("boolean");

                    b.Property<string>("KonumIFrame")
                        .HasColumnType("text");

                    b.Property<string>("Landscape")
                        .HasColumnType("text");

                    b.Property<int>("LivingRoomCount")
                        .HasColumnType("integer");

                    b.Property<double?>("LocationLat")
                        .HasColumnType("double precision");

                    b.Property<double?>("LocationLon")
                        .HasColumnType("double precision");

                    b.Property<long>("NeighborhoodId")
                        .HasColumnType("bigint");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<long>("PropertyStatusId")
                        .HasColumnType("bigint");

                    b.Property<long>("PropertyTypeId")
                        .HasColumnType("bigint");

                    b.Property<int>("RoomCount")
                        .HasColumnType("integer");

                    b.Property<string>("SiteName")
                        .HasColumnType("text");

                    b.Property<long?>("StreetId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UsableSquareMeter")
                        .HasColumnType("integer");

                    b.Property<long>("UsingStatusId")
                        .HasColumnType("bigint");

                    b.Property<string>("YoutubeLink")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("CityId");

                    b.HasIndex("ClientId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("DeedStatusId");

                    b.HasIndex("DistrictId");

                    b.HasIndex("FrontId");

                    b.HasIndex("HeatingTypeId");

                    b.HasIndex("InternetTypeId");

                    b.HasIndex("NeighborhoodId");

                    b.HasIndex("PropertyStatusId");

                    b.HasIndex("PropertyTypeId");

                    b.HasIndex("StreetId");

                    b.HasIndex("UsingStatusId");

                    b.ToTable("Properties");
                });

            modelBuilder.Entity("RealEstateWebApi.Domain.Entities.PropertyStatus", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("PropertyStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedDate = new DateTime(2022, 11, 18, 11, 19, 21, 995, DateTimeKind.Utc).AddTicks(8303),
                            IsActive = true,
                            IsDeleted = false,
                            Title = "Satılık"
                        },
                        new
                        {
                            Id = 2L,
                            CreatedDate = new DateTime(2022, 11, 18, 11, 19, 21, 995, DateTimeKind.Utc).AddTicks(8308),
                            IsActive = true,
                            IsDeleted = false,
                            Title = "Kiralık"
                        },
                        new
                        {
                            Id = 3L,
                            CreatedDate = new DateTime(2022, 11, 18, 11, 19, 21, 995, DateTimeKind.Utc).AddTicks(8309),
                            IsActive = true,
                            IsDeleted = false,
                            Title = "Devren Satılık"
                        },
                        new
                        {
                            Id = 4L,
                            CreatedDate = new DateTime(2022, 11, 18, 11, 19, 21, 995, DateTimeKind.Utc).AddTicks(8310),
                            IsActive = true,
                            IsDeleted = false,
                            Title = "Devren Kiralık"
                        });
                });

            modelBuilder.Entity("RealEstateWebApi.Domain.Entities.PropertyType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("PropertyTypes");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedDate = new DateTime(2022, 11, 18, 11, 19, 21, 995, DateTimeKind.Utc).AddTicks(9083),
                            IsActive = true,
                            IsDeleted = false,
                            Title = "Daire"
                        },
                        new
                        {
                            Id = 2L,
                            CreatedDate = new DateTime(2022, 11, 18, 11, 19, 21, 995, DateTimeKind.Utc).AddTicks(9087),
                            IsActive = true,
                            IsDeleted = false,
                            Title = "Residans"
                        },
                        new
                        {
                            Id = 3L,
                            CreatedDate = new DateTime(2022, 11, 18, 11, 19, 21, 995, DateTimeKind.Utc).AddTicks(9089),
                            IsActive = true,
                            IsDeleted = false,
                            Title = "Müstakil Ev"
                        },
                        new
                        {
                            Id = 4L,
                            CreatedDate = new DateTime(2022, 11, 18, 11, 19, 21, 995, DateTimeKind.Utc).AddTicks(9090),
                            IsActive = true,
                            IsDeleted = false,
                            Title = "Müstakil Bina"
                        },
                        new
                        {
                            Id = 5L,
                            CreatedDate = new DateTime(2022, 11, 18, 11, 19, 21, 995, DateTimeKind.Utc).AddTicks(9091),
                            IsActive = true,
                            IsDeleted = false,
                            Title = "Villa"
                        },
                        new
                        {
                            Id = 6L,
                            CreatedDate = new DateTime(2022, 11, 18, 11, 19, 21, 995, DateTimeKind.Utc).AddTicks(9093),
                            IsActive = true,
                            IsDeleted = false,
                            Title = "Çiftlik Evi"
                        },
                        new
                        {
                            Id = 7L,
                            CreatedDate = new DateTime(2022, 11, 18, 11, 19, 21, 995, DateTimeKind.Utc).AddTicks(9094),
                            IsActive = true,
                            IsDeleted = false,
                            Title = "Yazlık"
                        },
                        new
                        {
                            Id = 8L,
                            CreatedDate = new DateTime(2022, 11, 18, 11, 19, 21, 995, DateTimeKind.Utc).AddTicks(9096),
                            IsActive = true,
                            IsDeleted = false,
                            Title = "Büro/Ofis"
                        },
                        new
                        {
                            Id = 9L,
                            CreatedDate = new DateTime(2022, 11, 18, 11, 19, 21, 995, DateTimeKind.Utc).AddTicks(9097),
                            IsActive = true,
                            IsDeleted = false,
                            Title = "Depo/Antrepo"
                        },
                        new
                        {
                            Id = 10L,
                            CreatedDate = new DateTime(2022, 11, 18, 11, 19, 21, 995, DateTimeKind.Utc).AddTicks(9099),
                            IsActive = true,
                            IsDeleted = false,
                            Title = "Dükkan/Mağaza"
                        },
                        new
                        {
                            Id = 11L,
                            CreatedDate = new DateTime(2022, 11, 18, 11, 19, 21, 995, DateTimeKind.Utc).AddTicks(9100),
                            IsActive = true,
                            IsDeleted = false,
                            Title = "Plaza"
                        },
                        new
                        {
                            Id = 12L,
                            CreatedDate = new DateTime(2022, 11, 18, 11, 19, 21, 995, DateTimeKind.Utc).AddTicks(9101),
                            IsActive = true,
                            IsDeleted = false,
                            Title = "Palaza Katı"
                        },
                        new
                        {
                            Id = 13L,
                            CreatedDate = new DateTime(2022, 11, 18, 11, 19, 21, 995, DateTimeKind.Utc).AddTicks(9103),
                            IsActive = true,
                            IsDeleted = false,
                            Title = "Sağlık Merkezi"
                        },
                        new
                        {
                            Id = 14L,
                            CreatedDate = new DateTime(2022, 11, 18, 11, 19, 21, 995, DateTimeKind.Utc).AddTicks(9104),
                            IsActive = true,
                            IsDeleted = false,
                            Title = "Spor Tesisi"
                        });
                });

            modelBuilder.Entity("RealEstateWebApi.Domain.Entities.ShortProperty", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CityId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("DistrictId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int?>("LivingRoomCount")
                        .HasColumnType("integer");

                    b.Property<long?>("NeighborhoodId")
                        .HasColumnType("bigint");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<long>("PropertyStatusId")
                        .HasColumnType("bigint");

                    b.Property<long>("PropertyTypeId")
                        .HasColumnType("bigint");

                    b.Property<int?>("RoomCount")
                        .HasColumnType("integer");

                    b.Property<long?>("StreetId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("DistrictId");

                    b.HasIndex("NeighborhoodId");

                    b.HasIndex("PropertyStatusId");

                    b.HasIndex("PropertyTypeId");

                    b.HasIndex("StreetId");

                    b.ToTable("ShortProperties");
                });

            modelBuilder.Entity("RealEstateWebApi.Domain.Entities.Street", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NeighborhoodKey")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Streets");
                });

            modelBuilder.Entity("RealEstateWebApi.Domain.Entities.UsingStatus", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("UsingStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedDate = new DateTime(2022, 11, 18, 11, 19, 22, 1, DateTimeKind.Utc).AddTicks(4515),
                            IsActive = true,
                            IsDeleted = false,
                            Title = "Boş"
                        },
                        new
                        {
                            Id = 2L,
                            CreatedDate = new DateTime(2022, 11, 18, 11, 19, 22, 1, DateTimeKind.Utc).AddTicks(4519),
                            IsActive = true,
                            IsDeleted = false,
                            Title = "Mülk Sahibi"
                        },
                        new
                        {
                            Id = 3L,
                            CreatedDate = new DateTime(2022, 11, 18, 11, 19, 22, 1, DateTimeKind.Utc).AddTicks(4521),
                            IsActive = true,
                            IsDeleted = false,
                            Title = "Kiracılı"
                        });
                });

            modelBuilder.Entity("RealEstateWebApi.Domain.Entities.PropertyPhoto", b =>
                {
                    b.HasBaseType("RealEstateWebApi.Domain.Entities.File");

                    b.Property<long>("PropertyId")
                        .HasColumnType("bigint");

                    b.Property<int>("SortIndex")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("PropertyPhoto");
                });

            modelBuilder.Entity("RealEstateWebApi.Domain.Entities.Agent", b =>
                {
                    b.HasOne("RealEstateWebApi.Domain.Entities.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RealEstateWebApi.Domain.Entities.Identity.User", null)
                        .WithOne()
                        .HasForeignKey("RealEstateWebApi.Domain.Entities.Agent", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RealEstateWebApi.Domain.Entities.JobTitle", null)
                        .WithMany()
                        .HasForeignKey("JobTitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RealEstateWebApi.Domain.Entities.Blog", b =>
                {
                    b.HasOne("RealEstateWebApi.Domain.Entities.Agent", null)
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RealEstateWebApi.Domain.Entities.File", null)
                        .WithMany()
                        .HasForeignKey("BlogPageImgFileId");

                    b.HasOne("RealEstateWebApi.Domain.Entities.BlogType", null)
                        .WithMany()
                        .HasForeignKey("BlogTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RealEstateWebApi.Domain.Entities.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RealEstateWebApi.Domain.Entities.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RealEstateWebApi.Domain.Entities.BlogType", b =>
                {
                    b.HasOne("RealEstateWebApi.Domain.Entities.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RealEstateWebApi.Domain.Entities.Client", b =>
                {
                    b.HasOne("RealEstateWebApi.Domain.Entities.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RealEstateWebApi.Domain.Entities.File", null)
                        .WithMany()
                        .HasForeignKey("LogoImgFileId");
                });

            modelBuilder.Entity("RealEstateWebApi.Domain.Entities.Customer", b =>
                {
                    b.HasOne("RealEstateWebApi.Domain.Entities.City", null)
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RealEstateWebApi.Domain.Entities.District", null)
                        .WithMany()
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RealEstateWebApi.Domain.Entities.Neighborhood", null)
                        .WithMany()
                        .HasForeignKey("NeighborhoodId");
                });

            modelBuilder.Entity("RealEstateWebApi.Domain.Entities.CustomerOwnedShortProperty", b =>
                {
                    b.HasOne("RealEstateWebApi.Domain.Entities.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RealEstateWebApi.Domain.Entities.Property", null)
                        .WithMany()
                        .HasForeignKey("PropertyId");

                    b.HasOne("RealEstateWebApi.Domain.Entities.ShortProperty", null)
                        .WithMany()
                        .HasForeignKey("ShortPropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RealEstateWebApi.Domain.Entities.CustomerSearchShortProperty", b =>
                {
                    b.HasOne("RealEstateWebApi.Domain.Entities.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RealEstateWebApi.Domain.Entities.ShortProperty", null)
                        .WithMany()
                        .HasForeignKey("ShortPropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RealEstateWebApi.Domain.Entities.Entry", b =>
                {
                    b.HasOne("RealEstateWebApi.Domain.Entities.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RealEstateWebApi.Domain.Entities.EntrySubType", null)
                        .WithMany()
                        .HasForeignKey("EntrySubTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RealEstateWebApi.Domain.Entities.EntryType", null)
                        .WithMany()
                        .HasForeignKey("EntryTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RealEstateWebApi.Domain.Entities.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RealEstateWebApi.Domain.Entities.EntrySubType", b =>
                {
                    b.HasOne("RealEstateWebApi.Domain.Entities.EntryType", null)
                        .WithMany()
                        .HasForeignKey("EntryTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RealEstateWebApi.Domain.Entities.Identity.User", b =>
                {
                    b.HasOne("RealEstateWebApi.Domain.Entities.File", null)
                        .WithMany()
                        .HasForeignKey("ProfileImgFileId");
                });

            modelBuilder.Entity("RealEstateWebApi.Domain.Entities.Identity.UserOperationClaim", b =>
                {
                    b.HasOne("RealEstateWebApi.Domain.Entities.Identity.OperationClaim", null)
                        .WithMany()
                        .HasForeignKey("OperationClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RealEstateWebApi.Domain.Entities.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RealEstateWebApi.Domain.Entities.JobTitle", b =>
                {
                    b.HasOne("RealEstateWebApi.Domain.Entities.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RealEstateWebApi.Domain.Entities.Message", b =>
                {
                    b.HasOne("RealEstateWebApi.Domain.Entities.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RealEstateWebApi.Domain.Entities.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RealEstateWebApi.Domain.Entities.Property", b =>
                {
                    b.HasOne("RealEstateWebApi.Domain.Entities.Agent", null)
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RealEstateWebApi.Domain.Entities.City", null)
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RealEstateWebApi.Domain.Entities.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientId");

                    b.HasOne("RealEstateWebApi.Domain.Entities.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RealEstateWebApi.Domain.Entities.DeedStatus", null)
                        .WithMany()
                        .HasForeignKey("DeedStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RealEstateWebApi.Domain.Entities.District", null)
                        .WithMany()
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RealEstateWebApi.Domain.Entities.Front", null)
                        .WithMany()
                        .HasForeignKey("FrontId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RealEstateWebApi.Domain.Entities.HeatingType", null)
                        .WithMany()
                        .HasForeignKey("HeatingTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RealEstateWebApi.Domain.Entities.InternetType", null)
                        .WithMany()
                        .HasForeignKey("InternetTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RealEstateWebApi.Domain.Entities.Neighborhood", null)
                        .WithMany()
                        .HasForeignKey("NeighborhoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RealEstateWebApi.Domain.Entities.PropertyStatus", null)
                        .WithMany()
                        .HasForeignKey("PropertyStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RealEstateWebApi.Domain.Entities.PropertyType", null)
                        .WithMany()
                        .HasForeignKey("PropertyTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RealEstateWebApi.Domain.Entities.Street", null)
                        .WithMany()
                        .HasForeignKey("StreetId");

                    b.HasOne("RealEstateWebApi.Domain.Entities.UsingStatus", null)
                        .WithMany()
                        .HasForeignKey("UsingStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RealEstateWebApi.Domain.Entities.ShortProperty", b =>
                {
                    b.HasOne("RealEstateWebApi.Domain.Entities.City", null)
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RealEstateWebApi.Domain.Entities.District", null)
                        .WithMany()
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RealEstateWebApi.Domain.Entities.Neighborhood", null)
                        .WithMany()
                        .HasForeignKey("NeighborhoodId");

                    b.HasOne("RealEstateWebApi.Domain.Entities.PropertyStatus", null)
                        .WithMany()
                        .HasForeignKey("PropertyStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RealEstateWebApi.Domain.Entities.PropertyType", null)
                        .WithMany()
                        .HasForeignKey("PropertyTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RealEstateWebApi.Domain.Entities.Street", null)
                        .WithMany()
                        .HasForeignKey("StreetId");
                });
#pragma warning restore 612, 618
        }
    }
}
