// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RealEstateWebApi.Persistence.Contexts;

#nullable disable

namespace RealEstateWebApi.Persistence.Migrations
{
    [DbContext(typeof(RealEstateWebApiDbContext))]
    [Migration("20220710191512_mig_8")]
    partial class mig_8
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RealEstateWebApi.Domain.Entities.Agent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("FacebookUrl")
                        .HasColumnType("text");

                    b.Property<string>("InstagramUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<long>("JobTitleId")
                        .HasColumnType("bigint");

                    b.Property<string>("LinkedinUrl")
                        .HasColumnType("text");

                    b.Property<string>("TwitterUrl")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ViewMobileNumber")
                        .HasColumnType("text");

                    b.Property<string>("ViewPhoneNumber")
                        .HasColumnType("text");

                    b.Property<string>("YoutubeProfileUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("JobTitleId");

                    b.ToTable("Agents");
                });

            modelBuilder.Entity("RealEstateWebApi.Domain.Entities.Blog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AgentId")
                        .HasColumnType("bigint");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("BlogPageImgFileId")
                        .HasColumnType("bigint");

                    b.Property<long>("BlogTypeId")
                        .HasColumnType("bigint");

                    b.Property<long>("ClientId")
                        .HasColumnType("bigint");

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("BlogPageImgFileId");

                    b.HasIndex("BlogTypeId");

                    b.HasIndex("ClientId");

                    b.HasIndex("CompanyId");

                    b.ToTable("Blogs");
                });

            modelBuilder.Entity("RealEstateWebApi.Domain.Entities.BlogType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ClientId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("BlogTypes");
                });

            modelBuilder.Entity("RealEstateWebApi.Domain.Entities.City", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Key")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("RealEstateWebApi.Domain.Entities.Client", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("About")
                        .HasColumnType("text");

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<string>("ContactAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Dns")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FacebookUrl")
                        .HasColumnType("text");

                    b.Property<string>("InstagramUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LinkedinUrl")
                        .HasColumnType("text");

                    b.Property<long?>("LogoImgFileId")
                        .HasColumnType("bigint");

                    b.Property<string>("SummaryInfo")
                        .HasColumnType("text");

                    b.Property<string>("TwitterUrl")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ViewName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("LogoImgFileId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("RealEstateWebApi.Domain.Entities.Company", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("StartingYear")
                        .HasColumnType("integer");

                    b.Property<string>("TaxAdministration")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("TaxNumber")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("RealEstateWebApi.Domain.Entities.DeedStatus", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("DeedStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedDate = new DateTime(2022, 7, 10, 19, 15, 11, 546, DateTimeKind.Utc).AddTicks(6127),
                            IsActive = true,
                            Title = "Kat Mülkiyetli"
                        },
                        new
                        {
                            Id = 2L,
                            CreatedDate = new DateTime(2022, 7, 10, 19, 15, 11, 546, DateTimeKind.Utc).AddTicks(6132),
                            IsActive = true,
                            Title = "Kat İrtifaklı"
                        },
                        new
                        {
                            Id = 3L,
                            CreatedDate = new DateTime(2022, 7, 10, 19, 15, 11, 546, DateTimeKind.Utc).AddTicks(6134),
                            IsActive = true,
                            Title = "Arsa"
                        },
                        new
                        {
                            Id = 4L,
                            CreatedDate = new DateTime(2022, 7, 10, 19, 15, 11, 546, DateTimeKind.Utc).AddTicks(6135),
                            IsActive = true,
                            Title = "Tarla"
                        });
                });

            modelBuilder.Entity("RealEstateWebApi.Domain.Entities.District", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("CityKey")
                        .HasColumnType("integer");

                    b.Property<int>("Key")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Districts");
                });

            modelBuilder.Entity("RealEstateWebApi.Domain.Entities.File", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Storage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Files");

                    b.HasDiscriminator<string>("Discriminator").HasValue("File");
                });

            modelBuilder.Entity("RealEstateWebApi.Domain.Entities.Front", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Fronts");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedDate = new DateTime(2022, 7, 10, 19, 15, 11, 546, DateTimeKind.Utc).AddTicks(6978),
                            IsActive = true,
                            Title = "Kuzey"
                        },
                        new
                        {
                            Id = 2L,
                            CreatedDate = new DateTime(2022, 7, 10, 19, 15, 11, 546, DateTimeKind.Utc).AddTicks(6982),
                            IsActive = true,
                            Title = "Kuzey Doğu"
                        },
                        new
                        {
                            Id = 3L,
                            CreatedDate = new DateTime(2022, 7, 10, 19, 15, 11, 546, DateTimeKind.Utc).AddTicks(6983),
                            IsActive = true,
                            Title = "Doğu"
                        },
                        new
                        {
                            Id = 4L,
                            CreatedDate = new DateTime(2022, 7, 10, 19, 15, 11, 546, DateTimeKind.Utc).AddTicks(6985),
                            IsActive = true,
                            Title = "Güney Doğu"
                        },
                        new
                        {
                            Id = 5L,
                            CreatedDate = new DateTime(2022, 7, 10, 19, 15, 11, 546, DateTimeKind.Utc).AddTicks(6986),
                            IsActive = true,
                            Title = "Güney"
                        },
                        new
                        {
                            Id = 6L,
                            CreatedDate = new DateTime(2022, 7, 10, 19, 15, 11, 546, DateTimeKind.Utc).AddTicks(6987),
                            IsActive = true,
                            Title = "Güney Batı"
                        },
                        new
                        {
                            Id = 7L,
                            CreatedDate = new DateTime(2022, 7, 10, 19, 15, 11, 546, DateTimeKind.Utc).AddTicks(6989),
                            IsActive = true,
                            Title = "Batı"
                        },
                        new
                        {
                            Id = 8L,
                            CreatedDate = new DateTime(2022, 7, 10, 19, 15, 11, 546, DateTimeKind.Utc).AddTicks(6990),
                            IsActive = true,
                            Title = "Kuzey Batı"
                        });
                });

            modelBuilder.Entity("RealEstateWebApi.Domain.Entities.HeatingType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("HeatingTypes");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedDate = new DateTime(2022, 7, 10, 19, 15, 11, 546, DateTimeKind.Utc).AddTicks(7660),
                            IsActive = true,
                            Title = "Doğalgaz Sobalı"
                        },
                        new
                        {
                            Id = 2L,
                            CreatedDate = new DateTime(2022, 7, 10, 19, 15, 11, 546, DateTimeKind.Utc).AddTicks(7663),
                            IsActive = true,
                            Title = "Sobalı"
                        },
                        new
                        {
                            Id = 3L,
                            CreatedDate = new DateTime(2022, 7, 10, 19, 15, 11, 546, DateTimeKind.Utc).AddTicks(7665),
                            IsActive = true,
                            Title = "Yerden Isıtma"
                        },
                        new
                        {
                            Id = 4L,
                            CreatedDate = new DateTime(2022, 7, 10, 19, 15, 11, 546, DateTimeKind.Utc).AddTicks(7666),
                            IsActive = true,
                            Title = "Kombili"
                        },
                        new
                        {
                            Id = 5L,
                            CreatedDate = new DateTime(2022, 7, 10, 19, 15, 11, 546, DateTimeKind.Utc).AddTicks(7668),
                            IsActive = true,
                            Title = "Merkezi Sistem"
                        },
                        new
                        {
                            Id = 6L,
                            CreatedDate = new DateTime(2022, 7, 10, 19, 15, 11, 546, DateTimeKind.Utc).AddTicks(7669),
                            IsActive = true,
                            Title = "FuelOil"
                        });
                });

            modelBuilder.Entity("RealEstateWebApi.Domain.Entities.Identity.OperationClaim", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Alias")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("OperationClaims");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Alias = "ADMIN",
                            CreatedDate = new DateTime(2022, 7, 10, 19, 15, 11, 548, DateTimeKind.Utc).AddTicks(5112),
                            Description = "Admin account",
                            IsActive = true,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2L,
                            Alias = "USER",
                            CreatedDate = new DateTime(2022, 7, 10, 19, 15, 11, 548, DateTimeKind.Utc).AddTicks(5116),
                            Description = "User account",
                            IsActive = true,
                            Name = "User"
                        },
                        new
                        {
                            Id = 3L,
                            Alias = "AGENT",
                            CreatedDate = new DateTime(2022, 7, 10, 19, 15, 11, 548, DateTimeKind.Utc).AddTicks(5118),
                            Description = "Agent account",
                            IsActive = true,
                            Name = "Agent"
                        });
                });

            modelBuilder.Entity("RealEstateWebApi.Domain.Entities.Identity.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("CitizenNumber")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("PassHash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("PassSalt")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<long?>("ProfileImgFileId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProfileImgFileId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RealEstateWebApi.Domain.Entities.Identity.UserLogin", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("RefreshTokenExpireDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("UserLogins");
                });

            modelBuilder.Entity("RealEstateWebApi.Domain.Entities.Identity.UserOperationClaim", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<long>("OperationClaimId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OperationClaimId");

                    b.HasIndex("UserId");

                    b.ToTable("UserOperationClaims");
                });

            modelBuilder.Entity("RealEstateWebApi.Domain.Entities.InternetType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("InternetTypes");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedDate = new DateTime(2022, 7, 10, 19, 15, 11, 546, DateTimeKind.Utc).AddTicks(8292),
                            IsActive = true,
                            Title = "Adsl/Vdsl"
                        },
                        new
                        {
                            Id = 2L,
                            CreatedDate = new DateTime(2022, 7, 10, 19, 15, 11, 546, DateTimeKind.Utc).AddTicks(8295),
                            IsActive = true,
                            Title = "Fiber"
                        },
                        new
                        {
                            Id = 3L,
                            CreatedDate = new DateTime(2022, 7, 10, 19, 15, 11, 546, DateTimeKind.Utc).AddTicks(8296),
                            IsActive = true,
                            Title = "Uydu"
                        },
                        new
                        {
                            Id = 4L,
                            CreatedDate = new DateTime(2022, 7, 10, 19, 15, 11, 546, DateTimeKind.Utc).AddTicks(8298),
                            IsActive = true,
                            Title = "Altyapı Yok"
                        });
                });

            modelBuilder.Entity("RealEstateWebApi.Domain.Entities.JobTitle", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("JobTitles");
                });

            modelBuilder.Entity("RealEstateWebApi.Domain.Entities.Message", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ClientId")
                        .HasColumnType("bigint");

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("SenderEmail")
                        .HasColumnType("text");

                    b.Property<string>("SenderMobile")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SenderName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("CompanyId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("RealEstateWebApi.Domain.Entities.Neighborhood", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("DistrictKey")
                        .HasColumnType("integer");

                    b.Property<int>("Key")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Neighborhoods");
                });

            modelBuilder.Entity("RealEstateWebApi.Domain.Entities.Property", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AgentId")
                        .HasColumnType("bigint");

                    b.Property<double?>("Aidat")
                        .HasColumnType("double precision");

                    b.Property<int?>("BalconyCount")
                        .HasColumnType("integer");

                    b.Property<int?>("BathRoomCount")
                        .HasColumnType("integer");

                    b.Property<int>("BuildingAge")
                        .HasColumnType("integer");

                    b.Property<int>("BuildingFloor")
                        .HasColumnType("integer");

                    b.Property<int>("BuildingTotalFloor")
                        .HasColumnType("integer");

                    b.Property<long>("CityId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ClientId")
                        .HasColumnType("bigint");

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("DeedStatusId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("DistrictId")
                        .HasColumnType("bigint");

                    b.Property<long>("FrontId")
                        .HasColumnType("bigint");

                    b.Property<int?>("GarageCount")
                        .HasColumnType("integer");

                    b.Property<int>("GrossSquareMeter")
                        .HasColumnType("integer");

                    b.Property<long>("HeatingTypeId")
                        .HasColumnType("bigint");

                    b.Property<long>("InternetTypeId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsAvailableLoan")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFurnished")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOnSite")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSmartHome")
                        .HasColumnType("boolean");

                    b.Property<string>("KonumIFrame")
                        .HasColumnType("text");

                    b.Property<string>("Landscape")
                        .HasColumnType("text");

                    b.Property<int>("LivingRoomCount")
                        .HasColumnType("integer");

                    b.Property<double?>("LocationLat")
                        .HasColumnType("double precision");

                    b.Property<double?>("LocationLon")
                        .HasColumnType("double precision");

                    b.Property<long>("NeighborhoodId")
                        .HasColumnType("bigint");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<long>("PropertyStatusId")
                        .HasColumnType("bigint");

                    b.Property<long>("PropertyTypeId")
                        .HasColumnType("bigint");

                    b.Property<int>("RoomCount")
                        .HasColumnType("integer");

                    b.Property<string>("SiteName")
                        .HasColumnType("text");

                    b.Property<long?>("StreetId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UsableSquareMeter")
                        .HasColumnType("integer");

                    b.Property<long>("UsingStatusId")
                        .HasColumnType("bigint");

                    b.Property<string>("YoutubeLink")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("CityId");

                    b.HasIndex("ClientId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("DeedStatusId");

                    b.HasIndex("DistrictId");

                    b.HasIndex("FrontId");

                    b.HasIndex("HeatingTypeId");

                    b.HasIndex("InternetTypeId");

                    b.HasIndex("NeighborhoodId");

                    b.HasIndex("PropertyStatusId");

                    b.HasIndex("PropertyTypeId");

                    b.HasIndex("UsingStatusId");

                    b.ToTable("Properties");
                });

            modelBuilder.Entity("RealEstateWebApi.Domain.Entities.PropertyStatus", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("PropertyStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedDate = new DateTime(2022, 7, 10, 19, 15, 11, 560, DateTimeKind.Utc).AddTicks(1620),
                            IsActive = true,
                            Title = "Satılık"
                        },
                        new
                        {
                            Id = 2L,
                            CreatedDate = new DateTime(2022, 7, 10, 19, 15, 11, 560, DateTimeKind.Utc).AddTicks(1625),
                            IsActive = true,
                            Title = "Kiralık"
                        },
                        new
                        {
                            Id = 3L,
                            CreatedDate = new DateTime(2022, 7, 10, 19, 15, 11, 560, DateTimeKind.Utc).AddTicks(1626),
                            IsActive = true,
                            Title = "Devren Satılık"
                        },
                        new
                        {
                            Id = 4L,
                            CreatedDate = new DateTime(2022, 7, 10, 19, 15, 11, 560, DateTimeKind.Utc).AddTicks(1628),
                            IsActive = true,
                            Title = "Devren Kiralık"
                        });
                });

            modelBuilder.Entity("RealEstateWebApi.Domain.Entities.PropertyType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("PropertyTypes");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedDate = new DateTime(2022, 7, 10, 19, 15, 11, 560, DateTimeKind.Utc).AddTicks(2471),
                            IsActive = true,
                            Title = "Daire"
                        },
                        new
                        {
                            Id = 2L,
                            CreatedDate = new DateTime(2022, 7, 10, 19, 15, 11, 560, DateTimeKind.Utc).AddTicks(2475),
                            IsActive = true,
                            Title = "Residans"
                        },
                        new
                        {
                            Id = 3L,
                            CreatedDate = new DateTime(2022, 7, 10, 19, 15, 11, 560, DateTimeKind.Utc).AddTicks(2476),
                            IsActive = true,
                            Title = "Müstakil Ev"
                        },
                        new
                        {
                            Id = 4L,
                            CreatedDate = new DateTime(2022, 7, 10, 19, 15, 11, 560, DateTimeKind.Utc).AddTicks(2478),
                            IsActive = true,
                            Title = "Müstakil Bina"
                        },
                        new
                        {
                            Id = 5L,
                            CreatedDate = new DateTime(2022, 7, 10, 19, 15, 11, 560, DateTimeKind.Utc).AddTicks(2479),
                            IsActive = true,
                            Title = "Villa"
                        },
                        new
                        {
                            Id = 6L,
                            CreatedDate = new DateTime(2022, 7, 10, 19, 15, 11, 560, DateTimeKind.Utc).AddTicks(2481),
                            IsActive = true,
                            Title = "Çiftlik Evi"
                        },
                        new
                        {
                            Id = 7L,
                            CreatedDate = new DateTime(2022, 7, 10, 19, 15, 11, 560, DateTimeKind.Utc).AddTicks(2482),
                            IsActive = true,
                            Title = "Yazlık"
                        },
                        new
                        {
                            Id = 8L,
                            CreatedDate = new DateTime(2022, 7, 10, 19, 15, 11, 560, DateTimeKind.Utc).AddTicks(2483),
                            IsActive = true,
                            Title = "Büro/Ofis"
                        },
                        new
                        {
                            Id = 9L,
                            CreatedDate = new DateTime(2022, 7, 10, 19, 15, 11, 560, DateTimeKind.Utc).AddTicks(2485),
                            IsActive = true,
                            Title = "Depo/Antrepo"
                        },
                        new
                        {
                            Id = 10L,
                            CreatedDate = new DateTime(2022, 7, 10, 19, 15, 11, 560, DateTimeKind.Utc).AddTicks(2486),
                            IsActive = true,
                            Title = "Dükkan/Mağaza"
                        },
                        new
                        {
                            Id = 11L,
                            CreatedDate = new DateTime(2022, 7, 10, 19, 15, 11, 560, DateTimeKind.Utc).AddTicks(2487),
                            IsActive = true,
                            Title = "Plaza"
                        },
                        new
                        {
                            Id = 12L,
                            CreatedDate = new DateTime(2022, 7, 10, 19, 15, 11, 560, DateTimeKind.Utc).AddTicks(2489),
                            IsActive = true,
                            Title = "Palaza Katı"
                        },
                        new
                        {
                            Id = 13L,
                            CreatedDate = new DateTime(2022, 7, 10, 19, 15, 11, 560, DateTimeKind.Utc).AddTicks(2490),
                            IsActive = true,
                            Title = "Sağlık Merkezi"
                        },
                        new
                        {
                            Id = 14L,
                            CreatedDate = new DateTime(2022, 7, 10, 19, 15, 11, 560, DateTimeKind.Utc).AddTicks(2491),
                            IsActive = true,
                            Title = "Spor Tesisi"
                        });
                });

            modelBuilder.Entity("RealEstateWebApi.Domain.Entities.Street", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NeighborhoodKey")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Streets");
                });

            modelBuilder.Entity("RealEstateWebApi.Domain.Entities.UsingStatus", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("UsingStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedDate = new DateTime(2022, 7, 10, 19, 15, 11, 561, DateTimeKind.Utc).AddTicks(9878),
                            IsActive = true,
                            Title = "Boş"
                        },
                        new
                        {
                            Id = 2L,
                            CreatedDate = new DateTime(2022, 7, 10, 19, 15, 11, 561, DateTimeKind.Utc).AddTicks(9881),
                            IsActive = true,
                            Title = "Mülk Sahibi"
                        },
                        new
                        {
                            Id = 3L,
                            CreatedDate = new DateTime(2022, 7, 10, 19, 15, 11, 561, DateTimeKind.Utc).AddTicks(9883),
                            IsActive = true,
                            Title = "Kiracılı"
                        });
                });

            modelBuilder.Entity("RealEstateWebApi.Domain.Entities.PropertyPhoto", b =>
                {
                    b.HasBaseType("RealEstateWebApi.Domain.Entities.File");

                    b.Property<long>("PropertyId")
                        .HasColumnType("bigint");

                    b.Property<int>("SortIndex")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("PropertyPhoto");
                });

            modelBuilder.Entity("RealEstateWebApi.Domain.Entities.Agent", b =>
                {
                    b.HasOne("RealEstateWebApi.Domain.Entities.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RealEstateWebApi.Domain.Entities.Identity.User", null)
                        .WithOne()
                        .HasForeignKey("RealEstateWebApi.Domain.Entities.Agent", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RealEstateWebApi.Domain.Entities.JobTitle", null)
                        .WithMany()
                        .HasForeignKey("JobTitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RealEstateWebApi.Domain.Entities.Blog", b =>
                {
                    b.HasOne("RealEstateWebApi.Domain.Entities.Agent", null)
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RealEstateWebApi.Domain.Entities.File", null)
                        .WithMany()
                        .HasForeignKey("BlogPageImgFileId");

                    b.HasOne("RealEstateWebApi.Domain.Entities.BlogType", null)
                        .WithMany()
                        .HasForeignKey("BlogTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RealEstateWebApi.Domain.Entities.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RealEstateWebApi.Domain.Entities.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RealEstateWebApi.Domain.Entities.BlogType", b =>
                {
                    b.HasOne("RealEstateWebApi.Domain.Entities.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RealEstateWebApi.Domain.Entities.Client", b =>
                {
                    b.HasOne("RealEstateWebApi.Domain.Entities.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RealEstateWebApi.Domain.Entities.File", null)
                        .WithMany()
                        .HasForeignKey("LogoImgFileId");
                });

            modelBuilder.Entity("RealEstateWebApi.Domain.Entities.Identity.User", b =>
                {
                    b.HasOne("RealEstateWebApi.Domain.Entities.File", null)
                        .WithMany()
                        .HasForeignKey("ProfileImgFileId");
                });

            modelBuilder.Entity("RealEstateWebApi.Domain.Entities.Identity.UserOperationClaim", b =>
                {
                    b.HasOne("RealEstateWebApi.Domain.Entities.Identity.OperationClaim", null)
                        .WithMany()
                        .HasForeignKey("OperationClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RealEstateWebApi.Domain.Entities.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RealEstateWebApi.Domain.Entities.JobTitle", b =>
                {
                    b.HasOne("RealEstateWebApi.Domain.Entities.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RealEstateWebApi.Domain.Entities.Message", b =>
                {
                    b.HasOne("RealEstateWebApi.Domain.Entities.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RealEstateWebApi.Domain.Entities.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RealEstateWebApi.Domain.Entities.Property", b =>
                {
                    b.HasOne("RealEstateWebApi.Domain.Entities.Agent", null)
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RealEstateWebApi.Domain.Entities.City", null)
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RealEstateWebApi.Domain.Entities.Street", null)
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RealEstateWebApi.Domain.Entities.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientId");

                    b.HasOne("RealEstateWebApi.Domain.Entities.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RealEstateWebApi.Domain.Entities.DeedStatus", null)
                        .WithMany()
                        .HasForeignKey("DeedStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RealEstateWebApi.Domain.Entities.District", null)
                        .WithMany()
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RealEstateWebApi.Domain.Entities.Front", null)
                        .WithMany()
                        .HasForeignKey("FrontId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RealEstateWebApi.Domain.Entities.HeatingType", null)
                        .WithMany()
                        .HasForeignKey("HeatingTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RealEstateWebApi.Domain.Entities.InternetType", null)
                        .WithMany()
                        .HasForeignKey("InternetTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RealEstateWebApi.Domain.Entities.Neighborhood", null)
                        .WithMany()
                        .HasForeignKey("NeighborhoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RealEstateWebApi.Domain.Entities.PropertyStatus", null)
                        .WithMany()
                        .HasForeignKey("PropertyStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RealEstateWebApi.Domain.Entities.PropertyType", null)
                        .WithMany()
                        .HasForeignKey("PropertyTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RealEstateWebApi.Domain.Entities.UsingStatus", null)
                        .WithMany()
                        .HasForeignKey("UsingStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
