using Microsoft.EntityFrameworkCore.Metadata.Builders;
using RealEstateWebApi.Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace RealEstateWebApi.Persistence.EntityConfigurations
{
    public class PropertyTypeEntityConfiguraiton : BaseConfiguration<PropertyType>
    {
        public override void Configure(EntityTypeBuilder<PropertyType> builder)
        {
            builder.HasOne<PropertyStatus>().WithMany().HasForeignKey(x=>x.PropertyStatusId);

            builder.HasData(
                    new PropertyType { Id = 1, PropertyStatusId = 1 , Title = "Daire", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 2, PropertyStatusId = 1 , Title = "Residence", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 3, PropertyStatusId = 1 , Title = "Müstakil Ev", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 4, PropertyStatusId = 1 , Title = "Villa", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 5, PropertyStatusId = 1 , Title = "Çiftlik Evi", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 6, PropertyStatusId = 1 , Title = "Köşk & Konak", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 7, PropertyStatusId = 1 , Title = "Yalı", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 8, PropertyStatusId = 1 , Title = "Yalı Dairesi", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 9, PropertyStatusId = 1 , Title = "Yazlık", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 10, PropertyStatusId = 1 , Title = "Prefabrik Ev", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 11, PropertyStatusId = 1 , Title = "Kooperatif", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 12, PropertyStatusId = 2 , Title = "Daire", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 13, PropertyStatusId = 2 , Title = "Residence", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 14, PropertyStatusId = 2 , Title = "Müstakil Ev", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 15, PropertyStatusId = 2 , Title = "Villa", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 16, PropertyStatusId = 2 , Title = "Çiftlik Evi", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 17, PropertyStatusId = 2 , Title = "Köşk & Konak", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 18, PropertyStatusId = 2 , Title = "Yalı", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 19, PropertyStatusId = 2 , Title = "Yalı Dairesi", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 20, PropertyStatusId = 3, Title = "Daire", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 21, PropertyStatusId = 3, Title = "Residence", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 22, PropertyStatusId = 3, Title = "Müstakil Ev", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 23, PropertyStatusId = 3, Title = "Villa", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 24, PropertyStatusId = 3, Title = "Çiftlik Evi", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 25, PropertyStatusId = 3, Title = "Köşk & Konak", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 26, PropertyStatusId = 3, Title = "Yalı", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 27, PropertyStatusId = 3, Title = "Yalı Dairesi", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 28, PropertyStatusId = 4, Title = "Daire", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 29, PropertyStatusId = 4, Title = "Villa", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 30, PropertyStatusId = 5 , Title = "Akaryakıt İstasyonu", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 31, PropertyStatusId = 5 , Title = "Apartman Dairesi", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 32, PropertyStatusId = 5 , Title = "Atölye ", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 33, PropertyStatusId = 5 , Title = "AVM", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 34, PropertyStatusId = 5 , Title = "Büfe", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 35, PropertyStatusId = 5 , Title = "Büro & Ofis", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 36, PropertyStatusId = 5 , Title = "Cafe & Bar", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 37, PropertyStatusId = 5 , Title = "Çiftlik", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 38, PropertyStatusId = 5 , Title = "Depo & Antrepo", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 39, PropertyStatusId = 5 , Title = "Düğün Salonu", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 40, PropertyStatusId = 5 , Title = "Dükkan & Mağaza", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 41, PropertyStatusId = 5 , Title = "Enerji Santralleri", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 42, PropertyStatusId = 5 , Title = "Fabrika", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 43, PropertyStatusId = 5 , Title = "Garaj & Park Yeri", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 44, PropertyStatusId = 5 , Title = "İmalathane ", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 45, PropertyStatusId = 5 , Title = "İş Hanı Katı & Ofisi", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 46, PropertyStatusId = 5 , Title = "Kantin", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 47, PropertyStatusId = 5 , Title = "Kır & Kahvaltı Bahçesi", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 48, PropertyStatusId = 5 , Title = "Kıraathane", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 49, PropertyStatusId = 5 , Title = "Komple Bina", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 50, PropertyStatusId = 5 , Title = "Maden Ocağı", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 51, PropertyStatusId = 5 , Title = "Otopark", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 52, PropertyStatusId = 5 , Title = "Pastane & Fırın", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 53, PropertyStatusId = 5 , Title = "Pazar Yeri", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 54, PropertyStatusId = 5 , Title = "Plaza", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 55, PropertyStatusId = 5 , Title = "Plaza Katı", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 56, PropertyStatusId = 5 , Title = "Prefabrik Yapı", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 57, PropertyStatusId = 5 , Title = "Radyo İstasyonu", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 58, PropertyStatusId = 5 , Title = "Residence Katı & Ofisi", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 59, PropertyStatusId = 5 , Title = "Restoran & Lokanta", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 60, PropertyStatusId = 5 , Title = "Sağlık Merkezi", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 61, PropertyStatusId = 5 , Title = "Sinema & Konferans Salonu", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 62, PropertyStatusId = 5 , Title = "SPA, Hamam & Sauna", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 63, PropertyStatusId = 5 , Title = "Spor Tesisi ", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 64, PropertyStatusId = 5 , Title = "Villa", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 65, PropertyStatusId = 5 , Title = "Yurt", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 66, PropertyStatusId = 6 , Title = "Akaryakıt İstasyonu", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 67, PropertyStatusId = 6 , Title = "Apartman Dairesi", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 68, PropertyStatusId = 6 , Title = "Atölye", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 69, PropertyStatusId = 6 , Title = "AVM", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 70, PropertyStatusId = 6 , Title = "Büfe", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 71, PropertyStatusId = 6 , Title = "Büro & Ofis", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 72, PropertyStatusId = 6 , Title = "Cafe & Bar", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 73, PropertyStatusId = 6 , Title = "Çiftlik", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 74, PropertyStatusId = 6 , Title = "Depo & Antrepo", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 75, PropertyStatusId = 6 , Title = "Düğün Salonu", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 76, PropertyStatusId = 6 , Title = "Dükkan & Mağaza", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 77, PropertyStatusId = 6 , Title = "Eczane & Medikal", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 78, PropertyStatusId = 6 , Title = "Fabrika", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 79, PropertyStatusId = 6 , Title = "Fotoğraf Stüdyosu", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 80, PropertyStatusId = 6 , Title = "Garaj", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 81, PropertyStatusId = 6 , Title = "Hazır & Sanal Ofis", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 82, PropertyStatusId = 6 , Title = "İmalathane", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 83, PropertyStatusId = 6 , Title = "İş Hanı Katı & Ofisi", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 84, PropertyStatusId = 6 , Title = "Kantin", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 85, PropertyStatusId = 6 , Title = "Kır & Kahvaltı Bahçesi ", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 86, PropertyStatusId = 6 , Title = "Kıraathane", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 87, PropertyStatusId = 6 , Title = "Komple Bina", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 88, PropertyStatusId = 6 , Title = "Kuaför & Güzellik Merkezi", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 89, PropertyStatusId = 6 , Title = "Maden Ocağı", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 90, PropertyStatusId = 6 , Title = "Market", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 91, PropertyStatusId = 6 , Title = "Muayenehane", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 92, PropertyStatusId = 6 , Title = "Okul & Kurs", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 93, PropertyStatusId = 6 , Title = "Otopark", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 94, PropertyStatusId = 6 , Title = "Oto Yıkama & Kuaför", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 95, PropertyStatusId = 6 , Title = "Pastane & Fırın", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 96, PropertyStatusId = 6 , Title = "Pazar Yeri", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 97, PropertyStatusId = 6 , Title = "Plaza", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 98, PropertyStatusId = 6 , Title = "Plaza Katı & Ofisi", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 99, PropertyStatusId = 6 , Title = "Prova & Kayıt Stüdyosu", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 100, PropertyStatusId = 6 , Title = "Radyo İstasyonu & TV Kanalı", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 101, PropertyStatusId = 6 , Title = "Residence Katı & Ofisi", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 102, PropertyStatusId = 6 , Title = "Restoran & Lokanta", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 103, PropertyStatusId = 6 , Title = "Sağlık Merkezi", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 104, PropertyStatusId = 6 , Title = "Sinema & Konferans Salonu", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 105, PropertyStatusId = 6 , Title = "Spa, Hamam & Sauna", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 106, PropertyStatusId = 6 , Title = "Spor Tesisi", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 107, PropertyStatusId = 6 , Title = "Taksi Durağı", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 108, PropertyStatusId = 6 , Title = "Tamirhane", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 109, PropertyStatusId = 6 , Title = "Villa", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 110, PropertyStatusId = 6 , Title = "Yurt", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 111, PropertyStatusId = 7 , Title = "Acente", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 112, PropertyStatusId = 7 , Title = "Akaryakıt İstasyonu", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 113, PropertyStatusId = 7 , Title = "Aktar & Baharatçı", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 114, PropertyStatusId = 7 , Title = "Anaokulu & Kreş", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 115, PropertyStatusId = 7 , Title = "Apartman Dairesi", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 116, PropertyStatusId = 7 , Title = "Araç Showroom & Servis", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 117, PropertyStatusId = 7 , Title = "Atölye", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 118, PropertyStatusId = 7 , Title = "AVM Standı", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 119, PropertyStatusId = 7 , Title = "Balıkçı", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 120, PropertyStatusId = 7 , Title = "Bar", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 121, PropertyStatusId = 7 , Title = "Bijuteri", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 122, PropertyStatusId = 7 , Title = "Börekçi", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 123, PropertyStatusId = 7 , Title = "Büfe", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 124, PropertyStatusId = 7 , Title = "Büro & Ofis", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 125, PropertyStatusId = 7 , Title = "Cafe", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 126, PropertyStatusId = 7 , Title = "CD & DVD Dükkanı", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 127, PropertyStatusId = 7 , Title = "Cep Telefonu Dükkanı", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 128, PropertyStatusId = 7 , Title = "Çamaşırhane", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 129, PropertyStatusId = 7 , Title = "Çay Ocağı", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 130, PropertyStatusId = 7 , Title = "Çiçekçi & Fidanlık", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 131, PropertyStatusId = 7 , Title = "Çiftlik", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 132, PropertyStatusId = 7 , Title = "Depo & Antrepo", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 133, PropertyStatusId = 7 , Title = "Düğün Salonu", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 134, PropertyStatusId = 7 , Title = "Dükkan & Mağaza", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 135, PropertyStatusId = 7 , Title = "Eczane & Medikal", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 136, PropertyStatusId = 7 , Title = "Elektrikçi & Hırdavatçı", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 137, PropertyStatusId = 7 , Title = "Elektronik Mağazası", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 138, PropertyStatusId = 7 , Title = "Etkinlik & Performans Salonu", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 139, PropertyStatusId = 7 , Title = "Fabrika & Üretim Tesisi", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 140, PropertyStatusId = 7 , Title = "Fatura Merkezi", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 141, PropertyStatusId = 7 , Title = "Fotoğraf Stüdyosu", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 142, PropertyStatusId = 7 , Title = "Gece Kulübü & Disko", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 143, PropertyStatusId = 7 , Title = "Giyim Mağazası", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 144, PropertyStatusId = 7 , Title = "Gözlükçü", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 145, PropertyStatusId = 7 , Title = "Halı Yıkama", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 146, PropertyStatusId = 7 , Title = "Huzur Evi", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 147, PropertyStatusId = 7 , Title = "İmalathane", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 148, PropertyStatusId = 7 , Title = "İnternet & Oyun Cafe", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 149, PropertyStatusId = 7 , Title = "İş Hanı", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 150, PropertyStatusId = 7 , Title = "İş Hanı Katı & Ofisi", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 151, PropertyStatusId = 7 , Title = "Kantin", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 152, PropertyStatusId = 7 , Title = "Kasap", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 153, PropertyStatusId = 7 , Title = "Kır & Kahvaltı Bahçesi ", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 154, PropertyStatusId = 7 , Title = "Kıraathane", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 155, PropertyStatusId = 7 , Title = "Kırtasiye", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 156, PropertyStatusId = 7 , Title = "Kozmetik Mağazası", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 157, PropertyStatusId = 7 , Title = "Kuaför & Güzellik Merkezi", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 158, PropertyStatusId = 7 , Title = "Kurs & Eğitim Merkezi", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 159, PropertyStatusId = 7 , Title = "Kuru Temizleme", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 160, PropertyStatusId = 7 , Title = "Kuruyemişçi", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 161, PropertyStatusId = 7 , Title = "Kuyumcu", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 162, PropertyStatusId = 7 , Title = "Lunapark", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 163, PropertyStatusId = 7 , Title = "Maden Ocağı", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 164, PropertyStatusId = 7 , Title = "Manav", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 165, PropertyStatusId = 7 , Title = "Market", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 166, PropertyStatusId = 7 , Title = "Matbaa", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 167, PropertyStatusId = 7 , Title = "Modaevi", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 168, PropertyStatusId = 7 , Title = "Muayenehane", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 169, PropertyStatusId = 7 , Title = "Nakliyat & Kargo", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 170, PropertyStatusId = 7 , Title = "Nalbur", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 171, PropertyStatusId = 7 , Title = "Okul", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 172, PropertyStatusId = 7 , Title = "Otopark / Garaj", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 173, PropertyStatusId = 7 , Title = "Oto Servis & Bakım", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 174, PropertyStatusId = 7 , Title = "Oto Yedek Parça", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 175, PropertyStatusId = 7 , Title = "Oto Yıkama & Kuaför", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 176, PropertyStatusId = 7 , Title = "Öğrenci Yurdu", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 177, PropertyStatusId = 7 , Title = "Pastane & Fırın & Tatlıcı", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 178, PropertyStatusId = 7 , Title = "Pazar Yeri", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 179, PropertyStatusId = 7 , Title = "Pet Shop", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 180, PropertyStatusId = 7 , Title = "Plaza", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 181, PropertyStatusId = 7 , Title = "Plaza Katı & Ofisi", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 182, PropertyStatusId = 7 , Title = "Prova & Kayıt Stüdyosu", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 183, PropertyStatusId = 7 , Title = "Radyo İstasyonu & TV Kanalı", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 184, PropertyStatusId = 7 , Title = "Residence Katı & Ofisi", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 185, PropertyStatusId = 7 , Title = "Restoran & Lokanta", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 186, PropertyStatusId = 7 , Title = "Saat Mağazası", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 187, PropertyStatusId = 7 , Title = "Sağlık Merkezi", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 188, PropertyStatusId = 7 , Title = "Sebze & Meyve Hali", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 189, PropertyStatusId = 7 , Title = "Sinema & Konferans Salonu", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 190, PropertyStatusId = 7 , Title = "Soğuk Hava Deposu", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 191, PropertyStatusId = 7 , Title = "SPA, Hamam & Sauna", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 192, PropertyStatusId = 7 , Title = "Spor Tesisi", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 193, PropertyStatusId = 7 , Title = "Su & Tüp Bayi", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 194, PropertyStatusId = 7 , Title = "Şans Oyunları Bayisi", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 195, PropertyStatusId = 7 , Title = "Şarküteri", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 196, PropertyStatusId = 7 , Title = "Taksi Durağı", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 197, PropertyStatusId = 7 , Title = "Tamirhane", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 198, PropertyStatusId = 7 , Title = "Tekel Bayi", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 199, PropertyStatusId = 7 , Title = "Teknik Servis", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 200, PropertyStatusId = 7 , Title = "Terzi", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 201, PropertyStatusId = 7 , Title = "Tuhafiye", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 202, PropertyStatusId = 7 , Title = "Veteriner", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 203, PropertyStatusId = 7 , Title = "Züccaciye", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 204, PropertyStatusId = 8 , Title = "Acente", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 205, PropertyStatusId = 8 , Title = "Akaryakıt İstasyonu", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 206, PropertyStatusId = 8 , Title = "Aktar & Baharatçı", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 207, PropertyStatusId = 8 , Title = "Anaokulu & Kreş", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 208, PropertyStatusId = 8 , Title = "Apartman Dairesi", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 209, PropertyStatusId = 8 , Title = "Araç Showroom & Servis", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 210, PropertyStatusId = 8 , Title = "Atölye", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 211, PropertyStatusId = 8 , Title = "AVM Standı", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 212, PropertyStatusId = 8 , Title = "Balıkçı", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 213, PropertyStatusId = 8 , Title = "Bar", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 214, PropertyStatusId = 8 , Title = "Bijuteri", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 215, PropertyStatusId = 8 , Title = "Börekçi", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 216, PropertyStatusId = 8 , Title = "Büfe", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 217, PropertyStatusId = 8 , Title = "Büro & Ofis", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 218, PropertyStatusId = 8 , Title = "Cafe", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 219, PropertyStatusId = 8 , Title = "CD & DVD Dükkanı", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 220, PropertyStatusId = 8 , Title = "Cep Telefonu Dükkanı", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 221, PropertyStatusId = 8 , Title = "Çamaşırhane", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 222, PropertyStatusId = 8 , Title = "Çay Ocağı", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 223, PropertyStatusId = 8 , Title = "Çiçekçi & Fidanlık", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 224, PropertyStatusId = 8 , Title = "Çiftlik", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 225, PropertyStatusId = 8 , Title = "Depo & Antrepo", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 226, PropertyStatusId = 8 , Title = "Düğün Salonu", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 227, PropertyStatusId = 8 , Title = "Dükkan & Mağaza", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 228, PropertyStatusId = 8 , Title = "Eczane", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 229, PropertyStatusId = 8 , Title = "Elektrikçi & Hırdavatçı", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 230, PropertyStatusId = 8 , Title = "Elektronik", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 231, PropertyStatusId = 8 , Title = "Fabrika", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 232, PropertyStatusId = 8 , Title = "Fatura Merkezi", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 233, PropertyStatusId = 8 , Title = "Fotoğraf Stüdyosu", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 234, PropertyStatusId = 8 , Title = "Gece Kulübü & Disko", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 235, PropertyStatusId = 8 , Title = "Giyim Mağazası", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 236, PropertyStatusId = 8 , Title = "Gözlükçü", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 237, PropertyStatusId = 8 , Title = "Halı Yıkama", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 238, PropertyStatusId = 8 , Title = "Huzur Evi", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 239, PropertyStatusId = 8 , Title = "İmalathane", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 240, PropertyStatusId = 8 , Title = "İnternet & Oyun Cafe", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 241, PropertyStatusId = 8 , Title = "İş Hanı", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 242, PropertyStatusId = 8 , Title = "İş Hanı Katı & Ofisi", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 243, PropertyStatusId = 8 , Title = "Kasap", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 244, PropertyStatusId = 8 , Title = "Kır & Kahvaltı Bahçesi ", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 245, PropertyStatusId = 8 , Title = "Kıraathane", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 246, PropertyStatusId = 8 , Title = "Kırtasiye", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 247, PropertyStatusId = 8 , Title = "Kozmetik Mağazası", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 248, PropertyStatusId = 8 , Title = "Kuaför & Güzellik Merkezi", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 249, PropertyStatusId = 8 , Title = "Kurs & Eğitim Merkezi", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 250, PropertyStatusId = 8 , Title = "Kuru Temizleme", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 251, PropertyStatusId = 8 , Title = "Kuruyemişçi", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 252, PropertyStatusId = 8 , Title = "Kuyumcu", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 253, PropertyStatusId = 8 , Title = "Lunapark", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 254, PropertyStatusId = 8 , Title = "Maden Ocağı", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 255, PropertyStatusId = 8 , Title = "Manav", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 256, PropertyStatusId = 8 , Title = "Market", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 257, PropertyStatusId = 8 , Title = "Matbaa", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 258, PropertyStatusId = 8 , Title = "Medikal Market", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 259, PropertyStatusId = 8 , Title = "Modaevi", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 260, PropertyStatusId = 8 , Title = "Muayenehane", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 261, PropertyStatusId = 8 , Title = "Nakliyat & Kargo", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 262, PropertyStatusId = 8 , Title = "Nalbur", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 263, PropertyStatusId = 8 , Title = "Okul", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 264, PropertyStatusId = 8 , Title = "Otopark / Garaj", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 265, PropertyStatusId = 8 , Title = "Oto Servis & Bakım", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 266, PropertyStatusId = 8 , Title = "Oto Yedek Parça", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 267, PropertyStatusId = 8 , Title = "Oto Yıkama & Kuaför", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 268, PropertyStatusId = 8 , Title = "Öğrenci Yurdu", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 269, PropertyStatusId = 8 , Title = "Pastane & Fırın", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 270, PropertyStatusId = 8 , Title = "Pazar Yeri", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 271, PropertyStatusId = 8 , Title = "Pet Shop", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 272, PropertyStatusId = 8 , Title = "Plaza", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 273, PropertyStatusId = 8 , Title = "Plaza Katı & Ofisi", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 274, PropertyStatusId = 8 , Title = "Prova & Kayıt Stüdyosu", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 275, PropertyStatusId = 8 , Title = "Radyo İstasyonu & TV Kanalı", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 276, PropertyStatusId = 8 , Title = "Residence Katı & Ofisi", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 277, PropertyStatusId = 8 , Title = "Restoran & Lokanta", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 278, PropertyStatusId = 8 , Title = "Saat Mağazası", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 279, PropertyStatusId = 8 , Title = "Sağlık Merkezi", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 280, PropertyStatusId = 8 , Title = "Sebze & Meyve Hali", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 281, PropertyStatusId = 8 , Title = "Sinema & Konferans Salonu", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 282, PropertyStatusId = 8 , Title = "Soğuk Hava Deposu", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 283, PropertyStatusId = 8 , Title = "SPA, Hamam & Sauna", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 284, PropertyStatusId = 8 , Title = "Spor Tesisi", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 285, PropertyStatusId = 8 , Title = "Su & Tüp Bayi", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 286, PropertyStatusId = 8 , Title = "Şans Oyunları Bayisi", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 287, PropertyStatusId = 8 , Title = "Şarküteri", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 288, PropertyStatusId = 8 , Title = "Taksi Durağı", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 289, PropertyStatusId = 8 , Title = "Tamirhane", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 290, PropertyStatusId = 8 , Title = "Tekel Bayi", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 291, PropertyStatusId = 8 , Title = "Teknik Servis", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 292, PropertyStatusId = 8 , Title = "Terzi", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 293, PropertyStatusId = 8 , Title = "Tuhafiye", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 294, PropertyStatusId = 8 , Title = "Tuvalet", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 295, PropertyStatusId = 8 , Title = "Veteriner", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 296, PropertyStatusId = 8 , Title = "Züccaciye", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 297, PropertyStatusId = 13 , Title = "Otel", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 298, PropertyStatusId = 13 , Title = "Apart Otel", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 299, PropertyStatusId = 13 , Title = "Butik Otel", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 300, PropertyStatusId = 13 , Title = "Motel", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 301, PropertyStatusId = 13 , Title = "Pansiyon", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 302, PropertyStatusId = 13 , Title = "Kamp Yeri (Mocamp)", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 303, PropertyStatusId = 13 , Title = "Tatil Köyü", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 304, PropertyStatusId = 14 , Title = "Otel", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 305, PropertyStatusId = 14 , Title = "Apart Otel", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 306, PropertyStatusId = 14 , Title = "Butik Otel", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 307, PropertyStatusId = 14 , Title = "Motel", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 308, PropertyStatusId = 14 , Title = "Pansiyon", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 309, PropertyStatusId = 14 , Title = "Kamp Yeri (Mocamp)", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 310, PropertyStatusId = 14 , Title = "Tatil Köyü", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() },
                    new PropertyType { Id = 311, PropertyStatusId = 14 , Title = "Plaj", CreatedDate = DateTime.MinValue.AddYears(2000).ToUniversalTime() }

                );

            builder.HasQueryFilter(p => p.IsDeleted == false);
            base.Configure(builder);
        }
    }
}
